### ISSUE TITLE
What is the best way to obtain an AUTO_ORG_TOKEN for new projects under Sensein?

### ISSUE THREAD

**Issue by fabiocat93** [sensein/python-package-template#2]
Hi @satra  ,

Could you specify the process for obtaining an AUTO_ORG_TOKEN and recommend the minimal privileges for a new project in general? Based on your feedback, I aim to refine our "Getting Started" guide.

Thanks for your input!
@fabiocat93

**Comment by satra** [comment]
this is now applicable to all org repos.

**Comment by hvgazula** [comment]
@satra had the same issue last evening with brain-bbqs and the workaround @fabiocat93 suggested was to create one within my github account developer settings and paste that in the org secrets. this is because i couldn't find a way to generate PATs under org. please advise.

**Comment by hvgazula** [comment]
Resolved. No PATs at the org level. Owners can create one individually and add it.
